language: android

before_script:
  - .buildscript/setup-emulator.sh

script:
  - ./disable.sh && ./disable-root.sh && ./update-blog-list.sh && ./update-list.sh

notifications:
  email: false

sudo: false

